version: "3"
services:
  web:
    build: .
    container_name: nginx-simple
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - web:/usr/share/nginx/html
      - errors:/usr/share/nginx/errors
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - php
  php:
    image: php:7.1.5-fpm-alpine
    container_name: nginx-simple-php
    volumes:
      - errors:/usr/share/nginx/errors
      - web:/usr/share/nginx/html

volumes:
  web:
  errors:
    
